fragment PageParts on Page {
  __typename
  title
  description
  keywords
  hero {
    __typename
    badge
    heading
    subheading
    image
    cta {
      __typename
      primaryText
      primaryLink
      secondaryText
      secondaryLink
    }
    stats {
      __typename
      value
      label
    }
  }
  body
}

fragment PostParts on Post {
  __typename
  title
  description
  keywords
  date
  author
  image
  category
  tags
  body
}

fragment PracticeAreaParts on PracticeArea {
  __typename
  title
  description
  keywords
  shortDescription
  icon
  order
  body
}

fragment CaseResultParts on CaseResult {
  __typename
  title
  caseType
  result
  summary
  date
  body
}

fragment TestimonialParts on Testimonial {
  __typename
  name
  caseType
  content
  rating
  date
  featured
}

fragment SettingsParts on Settings {
  __typename
  general {
    __typename
    siteName
    siteDescription
    logo
    favicon
  }
  contact {
    __typename
    phone
    email
    address
    hours
  }
  social {
    __typename
    facebook
    twitter
    linkedin
    instagram
  }
  seo {
    __typename
    defaultTitle
    defaultDescription
    defaultKeywords
    ogImage
  }
  colors {
    __typename
    primary
    secondary
    accent
  }
}
