
# Collection configurations for content types
collections_config:
  # Site Settings
  settings:
    path: content/settings
    name: Site Settings
    icon: settings
    disable_add: true
    disable_file_actions: true
    schemas:
      default:
        path: schemas/settings.md
    _enabled_editors:
      - data
  
  # Pages collection
  pages:
    path: content/pages
    name: Pages
    icon: description
    disable_add: false
    schemas:
      default:
        path: schemas/page.md
    _enabled_editors:
      - content
      - visual
  
  # Blog Posts / Industry News
  posts:
    path: content/posts
    name: Blog Posts
    icon: article
    sort_key: date
    sort:
      key: date
      order: desc
    schemas:
      default:
        path: schemas/post.md
    _enabled_editors:
      - content
      - visual
  
  # Practice Areas / Services
  practice_areas:
    path: content/practice-areas
    name: Practice Areas
    icon: gavel
    schemas:
      default:
        path: schemas/practice-area.md
    _enabled_editors:
      - content
  
  # Testimonials
  testimonials:
    path: content/testimonials
    name: Testimonials
    icon: format_quote
    schemas:
      default:
        path: schemas/testimonial.md
    _enabled_editors:
      - data
  
  # Case Results
  case_results:
    path: content/case-results
    name: Case Results
    icon: emoji_events
    schemas:
      default:
        path: schemas/case-result.md
    _enabled_editors:
      - data

# Schema definitions
_schema:
  # Settings Schema
  settings:
    - name: company
      label: Company Information
      type: object
      fields:
        - name: name
          label: Company Name
          type: string
          default: The Costello Law Group
        - name: tagline
          label: Tagline
          type: string
          default: Expert Legal Representation
        - name: description
          label: Description
          type: textarea
          default: The Costello Law Group delivers personalized legal solutions with proven results.
    
    - name: contact
      label: Contact Information
      type: object
      fields:
        - name: phone
          label: Phone Number
          type: string
          default: (954) 591-8099
        - name: email
          label: Email Address
          type: string
          default: joshua@thecostellolawgroup.com
        - name: address
          label: Address
          type: string
          default: 5846 S Flamingo Rd. Ste. 520, Cooper City, FL 33330
    
    - name: social
      label: Social Media
      type: object
      fields:
        - name: facebook
          label: Facebook URL
          type: string
        - name: twitter
          label: Twitter URL
          type: string
        - name: linkedin
          label: LinkedIn URL
          type: string
        - name: instagram
          label: Instagram URL
          type: string
    
    - name: theme
      label: Theme Colors
      type: object
      fields:
        - name: primary
          label: Primary Color (Teal)
          type: color
          default: '#00A878'
          comment: Main brand color used for buttons and accents
        - name: secondary
          label: Secondary Color (Navy)
          type: color
          default: '#0A1628'
          comment: Used for hero backgrounds and dark sections
        - name: accent
          label: Accent Color (Blue)
          type: color
          default: '#0066B2'
          comment: Used for links and secondary buttons
  
  # Page Schema
  page:
    - name: title
      label: Page Title
      type: string
      required: true
    
    - name: slug
      label: Page Slug
      type: string
      required: true
      comment: URL path for this page (e.g., /about, /contact)
    
    - name: hero
      label: Hero Section
      type: object
      fields:
        - name: heading
          label: Main Heading
          type: string
        - name: subheading
          label: Subheading
          type: textarea
        - name: cta_primary
          label: Primary Call-to-Action
          type: object
          fields:
            - name: text
              label: Button Text
              type: string
            - name: url
              label: Button URL
              type: string
        - name: cta_secondary
          label: Secondary Call-to-Action
          type: object
          fields:
            - name: text
              label: Button Text
              type: string
            - name: url
              label: Button URL
              type: string
        - name: background_color
          label: Background Color
          type: color
          default: '#0A1628'
    
    - name: content
      label: Page Content
      type: markdown
    
    - name: seo
      label: SEO Settings
      type: object
      fields:
        - name: title
          label: SEO Title
          type: string
        - name: description
          label: Meta Description
          type: textarea
        - name: keywords
          label: Keywords
          type: string
  
  # Blog Post Schema
  post:
    - name: title
      label: Post Title
      type: string
      required: true
    
    - name: slug
      label: URL Slug
      type: string
      required: true
    
    - name: date
      label: Publication Date
      type: date
      required: true
    
    - name: author
      label: Author
      type: string
      default: Joshua Costello, Esq.
    
    - name: excerpt
      label: Excerpt
      type: textarea
      comment: Short summary shown in listings
    
    - name: featured_image
      label: Featured Image
      type: image
      comment: Main image for the post
    
    - name: category
      label: Category
      type: select
      options:
        - Personal Injury
        - Auto Accidents
        - Insurance Claims
        - Criminal Defense
        - Legal News
        - Case Studies
    
    - name: tags
      label: Tags
      type: array
      comment: Keywords for the post
    
    - name: content
      label: Post Content
      type: markdown
    
    - name: seo
      label: SEO Settings
      type: object
      fields:
        - name: title
          label: SEO Title
          type: string
        - name: description
          label: Meta Description
          type: textarea
  
  # Practice Area Schema
  practice_area:
    - name: title
      label: Practice Area Title
      type: string
      required: true
    
    - name: slug
      label: URL Slug
      type: string
      required: true
    
    - name: icon
      label: Icon Name
      type: select
      options:
        - Car
        - Truck
        - Bike
        - Scale
        - HomeIcon
        - Dog
        - FileText
        - Gavel
        - Shield
        - Users
      comment: Icon to display for this practice area
    
    - name: description
      label: Short Description
      type: textarea
      comment: Brief description shown in cards
    
    - name: order
      label: Display Order
      type: number
      default: 0
      comment: Lower numbers appear first
    
    - name: featured
      label: Featured
      type: checkbox
      default: false
    
    - name: color
      label: Text Color
      type: string
      comment: Tailwind class like 'text-blue-600'
    
    - name: bg_color
      label: Background Color
      type: string
      comment: Tailwind class like 'bg-blue-50'
    
    - name: content
      label: Detailed Content
      type: markdown
    
    - name: services_offered
      label: Services Offered
      type: array
      comment: List of specific services
    
    - name: faq
      label: Frequently Asked Questions
      type: array
      comment: Common questions and answers
  
  # Testimonial Schema
  testimonial:
    - name: client_name
      label: Client Name
      type: string
      required: true
    
    - name: case_type
      label: Case Type
      type: string
      required: true
      comment: E.g., 'Personal Injury Client', 'Car Accident Client'
    
    - name: quote
      label: Testimonial Quote
      type: textarea
      required: true
    
    - name: rating
      label: Rating
      type: number
      default: 5
      comment: Star rating (1-5)
    
    - name: featured
      label: Featured
      type: checkbox
      default: false
      comment: Display on homepage
    
    - name: date
      label: Date
      type: date
      comment: When the testimonial was received
  
  # Case Result Schema
  case_result:
    - name: title
      label: Case Title
      type: string
      required: true
    
    - name: case_type
      label: Case Type
      type: select
      options:
        - Car Accident
        - Truck Accident
        - Motorcycle Accident
        - Slip and Fall
        - Premises Liability
        - Dog Bite
        - Wrongful Death
        - Insurance Claim
        - Criminal Defense
        - Other
    
    - name: settlement_amount
      label: Settlement Amount
      type: string
      comment: E.g., '$500,000' or 'Confidential'
    
    - name: description
      label: Case Description
      type: textarea
    
    - name: outcome
      label: Outcome
      type: textarea
    
    - name: featured
      label: Featured
      type: checkbox
      default: false
    
    - name: date
      label: Settlement Date
      type: date

# Global configuration
timezone: America/New_York

# Editor configuration
_editors:
  content:
    preview:
      text: Rich Text Editor
      subtext: Edit content with formatting
  visual:
    preview:
      text: Visual Editor
      subtext: Edit content visually on the page
  data:
    preview:
      text: Data Editor
      subtext: Edit structured data

# Source configuration
source: .

# Paths
paths:
  dam_uploads: public
  dam_static: ''
  static: public
  uploads: public

# Collections
collections:
  - path: content/pages
    name: Pages
    icon: description
  - path: content/posts
    name: Blog Posts
    icon: article
  - path: content/practice-areas
    name: Practice Areas
    icon: gavel
  - path: content/testimonials
    name: Testimonials
    icon: format_quote
  - path: content/case-results
    name: Case Results
    icon: emoji_events
  - path: content/settings
    name: Settings
    icon: settings

# Data configuration for content collections
_inputs:
  title:
    type: text
    comment: The title of the content
  description:
    type: textarea
    comment: A short description
  content:
    type: markdown
    comment: Main content area with rich text formatting
  date:
    type: datetime
    timezone: America/New_York
  color:
    type: color
  featured:
    type: checkbox
  rating:
    type: number
    min: 1
    max: 5
  image:
    type: image
  images:
    type: array
  tags:
    type: multiselect
    options:
      values:
        - Personal Injury
        - Auto Accidents
        - Insurance Claims
        - Legal Tips
        - Case Updates
        - Community News

# Brand colors from the website
_brand:
  primary: '#00A878'
  secondary: '#0A1628'
  accent: '#0066B2'

# Navigation structure
_structures:
  navigation:
    values:
      - label: Nav Item
        value:
          text:
          url:
          items:

# Site data
_site:
  name: The Costello Law Group
  tagline: Expert Legal Representation
  description: Personal injury, insurance claims, and criminal defense attorneys serving Broward County, Florida
  url: https://thecostellolawgroup.com
  
  # Contact information
  contact:
    phone: (954) 591-8099
    email: joshua@thecostellolawgroup.com
    address: 5846 S Flamingo Rd. Ste. 520, Cooper City, FL 33330
    
  # Service area
  service_area:
    - Cooper City, FL
    - Davie, FL
    - Plantation, FL
    - Pembroke Pines, FL
    - Broward County, FL
  
  # Social media
  social:
    facebook: https://www.facebook.com/costellolawgroup
    linkedin: https://www.linkedin.com/company/costello-law-group
    twitter: https://twitter.com/costellolawgrp
  
  # Practice areas
  practice_areas:
    - Car Accidents
    - Truck Accidents
    - Motorcycle Accidents
    - Slip & Fall
    - Premises Liability
    - Dog Bites
    - Wrongful Death
    - PIP Claims
    - Criminal Defense
    - Homeowners Insurance
  
  # Theme colors
  colors:
    primary: '#00A878'    # Teal - Main brand color
    secondary: '#0A1628'  # Navy - Dark backgrounds
    accent: '#0066B2'     # Blue - Links and secondary CTAs
    white: '#FFFFFF'
    gray_50: '#F9FAFB'
    gray_100: '#F3F4F6'
    gray_200: '#E5E7EB'
    gray_700: '#374151'
    gray_900: '#111827'