media:
  hero_images:
    folder: public/images/hero
    extensions:
      - jpg
      - jpeg
      - png
  general_images:
    folder: public/images
    extensions:
      - jpg
      - jpeg
      - png
      - svg
      - webp
  team_photos:
    folder: public/images/team
    extensions:
      - jpg
      - jpeg
      - png
  blog_images:
    folder: public/images/blog
    extensions:
      - jpg
      - jpeg
      - png
      - webp
  documents:
    folder: public/documents
    extensions:
      - pdf
      - doc
      - docx
  vector_assets:
    folder: public/images/icons
    extensions:
      - svg


components:
  seo:
    label: SEO
    type: object
    fields:
      - name: seo_title
        label: SEO Title
        type: string
        required: true
      - name: seo_description
        label: SEO Description
        type: string
        required: true
      - name: og_image
        label: OG Image
        type: image
        options:
          media: general_images
      - name: canonical_url
        label: Canonical URL
        type: string
      - name: schema_markup
        label: Schema
        type: code
        options:
          language: json

  hero_section:
    label: Hero
    type: object
    fields:
      - name: heading
        label: Heading
        type: string
        required: true
      - name: subheading
        label: Subheading
        type: text
      - name: background_image
        label: Background
        type: image
        options:
          media: hero_images
      - name: background_color
        label: BG Color
        type: string
      - name: text_color
        label: Text Color
        type: select
        options: [light, dark]
      - name: height
        label: Height
        type: select
        options: [small, medium, large]

  button:
    label: Button
    type: object
    fields:
      - name: text
        label: Text
        type: string
        required: true
      - name: link
        label: Link
        type: string
        required: true
      - name: style
        label: Style
        type: select
        options: [primary, secondary, outline, danger]
      - name: open_new_window
        label: New Window
        type: boolean

  social_links:
    label: Social
    type: object
    fields:
      - name: facebook
        label: Facebook
        type: string
      - name: twitter
        label: Twitter
        type: string
      - name: linkedin
        label: LinkedIn
        type: string
      - name: instagram
        label: Instagram
        type: string
      - name: youtube
        label: YouTube
        type: string

  contact_info:
    label: Contact
    type: object
    fields:
      - name: phone
        label: Phone
        type: string
        required: true
      - name: email
        label: Email
        type: string
      - name: address_line1
        label: Address
        type: string
        required: true
      - name: city
        label: City
        type: string
      - name: state
        label: State
        type: select
        options: [AL, AK, AZ, AR, CA, CO, CT, DE, FL, GA, HI, ID, IL, IN, IA, KS, KY, LA, ME, MD, MA, MI, MN, MS, MO, MT, NE, NV, NH, NJ, NM, NY, NC, ND, OH, OK, OR, PA, RI, SC, SD, TN, TX, UT, VT, VA, WA, WV, WI, WY]
      - name: zip_code
        label: ZIP
        type: string

content:
  - name: settings
    label: Site Settings
    type: file
    path: content/settings/site.json
    fields:
      - name: site_title
        label: Site Title
        type: string
        required: true
      - name: site_description
        label: Description
        type: text
      - name: logo
        label: Logo
        type: image
        options:
          media: general_images
      - name: color_scheme
        label: Colors
        type: object
        fields:
          - name: primary_color
            label: Primary
            type: string
          - name: secondary_color
            label: Secondary
            type: string
      - name: footer
        label: Footer
        type: object
        fields:
          - name: contact_info
            component: contact_info
          - name: social_links
            component: social_links

  - name: homepage
    label: Homepage
    type: file
    path: content/pages/home.json
    fields:
      - name: hero
        label: Hero
        component: hero_section
      - name: sections
        label: Sections
        type: block
        list: true
        blocks:
          - name: hero_cta
            label: Hero with CTA
            fields:
              - name: heading
                label: Heading
                type: string
              - name: image
                label: Image
                type: image
                options:
                  media: hero_images
              - name: buttons
                label: Buttons
                type: object
                list: true
                component: button
          - name: text_section
            label: Text
            fields:
              - name: title
                label: Title
                type: string
              - name: content
                label: Content
                type: rich-text
                options:
                  media: general_images
      - name: seo
        component: seo

  - name: pages
    label: Pages
    type: collection
    path: content/pages
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: body
        label: Content
        type: rich-text
        options:
          media: general_images
        required: true
      - name: seo
        component: seo
      - name: published
        label: Published
        type: boolean
        default: true
    view:
      fields: [title, published]
      sort: [title]
      search: [title, body]

  - name: blog
    label: Blog Posts
    type: collection
    path: content/posts
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: featured_image
        label: Image
        type: image
        options:
          media: blog_images
      - name: category
        label: Category
        type: select
        options: [Personal Injury, Auto Accidents, Insurance Claims, Criminal Defense]
      - name: tags
        label: Tags
        type: string
        list:
          min: 0
          max: 10
      - name: body
        label: Content
        type: rich-text
        options:
          media: general_images
        required: true
      - name: seo
        component: seo
    view:
      fields: [title, date, category]
      default:
        sort: date
        order: desc

  - name: practice_areas
    label: Practice Areas
    type: collection
    path: content/practice-areas
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: order
        label: Order
        type: number
      - name: body
        label: Content
        type: rich-text
        options:
          media: general_images
        required: true
      - name: seo
        component: seo
    view:
      fields: [title, order]
      sort: [order]

  - name: testimonials
    label: Testimonials
    type: collection
    path: content/testimonials
    format: json
    fields:
      - name: client_name
        label: Name
        type: string
        required: true
      - name: quote
        label: Quote
        type: text
        required: true
      - name: rating
        label: Rating
        type: number
        default: 5
        options:
          min: 1
          max: 5
      - name: featured
        label: Featured
        type: boolean
    view:
      fields: [client_name, rating, featured]
      sort: [rating]

  - name: team
    label: Team
    type: collection
    path: content/team
    format: json
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: photo
        label: Photo
        type: image
        options:
          media: team_photos
        required: true
      - name: bio
        label: Bio
        type: rich-text
        options:
          media: general_images
      - name: email
        label: Email
        type: string
      - name: phone
        label: Phone
        type: string
    view:
      fields: [name, title]
      sort: [name]

settings:
  content:
    merge: false
